package serverauth

import (
	"context"
	"time"
)

// AuditEvent is one immutable record of a security-relevant decision: a
// mutation, or a denial of any kind of request. The public server core builds
// one from the classified route and the outcome of authorization/execution and
// hands it to the installed Auditor; it never decides on its own whether an
// event is worth keeping.
type AuditEvent struct {
	// RequestID is the request's X-Request-ID (read from the incoming header
	// when present, otherwise generated by the core), so a client-visible
	// identifier ties a support report back to one audit row.
	RequestID string

	// Actor is the principal's Subject. Empty for a request the core rejected
	// before authentication produced one, and for the anonymous principal.
	Actor string

	// ActorKind classifies how Actor was established. The core sets it to the
	// principal's AuthMethod (for example "pat", "session", "bearer",
	// "anonymous"); a composition with a richer identity model (service
	// tokens, operator elevation) may want a finer-grained value and can
	// achieve that by having its Controller.Authenticate set a more specific
	// AuthMethod string.
	ActorKind string

	TenantID   string
	ProjectID  string
	Action     Action
	TargetType string
	TargetID   string

	// Outcome is one of "allowed", "denied", or "error".
	Outcome string

	At time.Time
}

// Auditor records a security-relevant event. The public server core calls
// Record for every mutation (object write, ref write, project create/rename)
// and for every denial (an Authorize error of any kind), but never for an
// allowed read — an audited system whose read traffic dominates its audit log
// stops being useful to search.
//
// Record must not block the request indefinitely; a composition that writes
// audit events to a remote sink should apply its own timeout and treat a
// failure to record as non-fatal to the request, logging it out of band
// instead. The self-hosted composition implements this by writing into its
// local audit_events table. The default (used when no Auditor is installed) is
// a no-op, matching today's open-mode behavior.
type Auditor interface {
	Record(ctx context.Context, event AuditEvent) error
}
